<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Gatehouse.Domain\Gatehouse.Domain.csproj" />
    <ProjectReference Include="..\Gatehouse.Application\Gatehouse.Application.csproj" />
    <ProjectReference Include="..\Gatehouse.Infrastructure\Gatehouse.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
